using FoodDelivery.Modules.Customers.RestockSubscriptions.Dtos;

namespace FoodDelivery.Modules.Customers.RestockSubscriptions.Features.CreatingRestockSubscription;

public record CreateRestockSubscriptionResponse(RestockSubscriptionDto RestockSubscription);
