# https://github.com/Huachao/vscode-restclient
@api-address=http://localhost:5000
@contentType = application/json

###
# @name ApiRoot
GET {{api-address}}
###

###
# @name Login
POST {{api-address}}/api/v1/identity/login
accept: application/json
Content-Type: application/json

{
  "userNameOrEmail": "mehdi",
  "password": "123456",
  "remember": true
}
###

###
# @name Register_New_User
POST {{api-address}}/api/v1/identity/users
accept: application/json
Content-Type: application/json

{
  "firstName": "mehdi4",
  "lastName": "test",
  "userName": "mehdi4",
  "email": "mehdi4@test.com",
  "password": "123456",
  "confirmPassword": "123456",
  "roles": [
    "user"
  ]
}
###

###
# @name Get_All_Users
@page=1
@pageSize=20
GET {{api-address}}/api/v1/identity/users?Page={{page}}&PageSize={{pageSize}}
accept: application/json
Content-Type: application/x-www-form-urlencoded
###

###
# @name Get_User_By_Email
@email=mehdi@test.com
GET {{api-address}}/api/v1/identity/users/by-email/{{email}}
accept: application/json
###


################################
# Identity-Server
################################
###
# @name OpenId_Configuration
GET {{api-address}}/.well-known/openid-configuration
###

###
# @name Get_oauthClient_Token
POST {{api-address}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=shop-api&client_id=oauthClient&client_secret=SuperSecretPassword
###


###
# @name Get_frontend-client_Token
POST {{api-address}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&scope=shop-api&client_id=frontend-client&username=mehdi&password=123456
###


###
# @name Authorize
POST {{api-address}}/connect/authorize
Content-Type: application/x-www-form-urlencoded

scope=shop-api&client_id=frontend-client
